samsung-cnct/cluster-api-provider-ssh

- clusterctl/examples/ssh/machines.yaml.template
I used the example from ConfigMaps to create this template.  MachineSpec contains our providerConfig.
Removed role, and containerRuntime since cluster-api removed them from the MachineSpec.
> Added providerConfig to spec, removed things gone from MachineSpec

- clusterctl/examples/ssh/README.md
- clusterctl/examples/ssh/generate-yaml.sh
The generate script has a key in it. It needs to be set as an env var. This pull request adds help text and documentation reflecting this step.
> Document key generation step

- Makefile
- README.md
* Get the git tree to the correct path
Changed the "obtaining the code" section to use git clone as go get
won't get a tree when the root of that tree has no "*.go" files.
* Use depend-update in case the GOPATH has old dependencies
If the GOPATH has old dependencies, "Solving failures" may happen as
those old dependencies will try to be used and may not have the needed
functions. Use the latest dependencies to prevent this problem.
> Fix readme

- clusterctl/examples/ssh/generate-yaml.sh
`[[` is not installed on lab nodes:
```
ubuntu@nuc-07:~/workspace/cluster-api-provider-ssh/clusterctl/examples/ssh$ ./generate-yaml.sh 
using empty pass phrase to private key
./generate-yaml.sh: 73: ./generate-yaml.sh: [[: not found
./generate-yaml.sh: 75: ./generate-yaml.sh: [[: not found
Unrecognized OS : Linux
ubuntu@nuc-07:~...
```
> Specify bash explicitly in shebang.

- README.md
Now that we're vendoring, we never want to update the vendor tree.
Remove that from the instructions.
> Remove `make depend-update` from readme

- clusterctl/examples/ssh/bootstrap_scripts/master_ubuntu_16.04.template
- clusterctl/examples/ssh/bootstrap_scripts/node_ubuntu_16.04.template
If a config file exists when apt tries to install or update a package,
it will error as there is no tty. Setting this variable to
noninteractive configures apt to run in a script.
> Set the DEBIAN_FRONTEND to noninteractive

- clusterctl/examples/ssh/bootstrap_scripts/master_ubuntu_16.04.template
In order for flannel to start successfully, the podCIDR needs to be
configured by kubeadm. Add it to the network section of the config yaml.
> Add the missing podCIDR to the kubeadm config

- cloud/ssh/actuators/machine/actuator_helper.go
The err string is nothing more than the exit code. Add the output of the
command to give context to the exit code.
> Make kubeadmToken errors useful

- README.md
- hack/clean-external-cluster.sh
Script added to had directory, including additional comments on Readme file. This should go away once clean up is merged, but for now this should save us all time.
> Script to clean external cluster

- cloud/ssh/actuators/machine/actuator.go
- cloud/ssh/actuators/machine/actuator_status.go
Reverts samsung-cnct/cluster-api-provider-ssh#67 There are two problems: 1) updateStatusAndAnnotations() will not add an annotation if Exists() fails, and Exists() will always fail if there is no annotation. 2) updateStatusAndAnnotations() attempts to make two updates using the same Machine object so that the second attempt will always fail.
> Revert "Cleanup annotation used to synchronize the deployer with the actuator"

- cloud/ssh/actuators/machine/actuator.go
- cloud/ssh/actuators/machine/actuator_helper.go
- cloud/ssh/actuators/machine/setupconfigs_metadata.go
- clusterctl/examples/ssh/bootstrap_scripts/master_bootstrap_ubuntu_16.04.template
- vendor/sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/clusterdeployer.go
Allows the use of the defined ip address when setting up kubernetes, while not using the default ip in networking config of the machine. Should alleviate issues we saw when trying to run against aws.
> Allows to configure kubeadm to use the IP address of the controlplane machine

- cloud/ssh/actuators/machine/actuator_helper.go
- cloud/ssh/actuators/machine/setupconfigs_metadata.go
**What this PR does / why we need it**:
This PR fixes a delete error when the control-plane node is deleted before the worker node, and the worker node delete was throwing an error.  In the case of delete, we should not be trying to ssh to the master node to create a token.  Token creation is only needed when a new node wants to join the cluster.  The attempt to run kubeadm on a deleted master was causing the error.  This fix allows deletion of the cluster in any order.
The code to create the kubeadm token on the master (using ssh) was moved to it's own method,
getKubeadmTokenOnMaster.  A ttl of ten minutes was added.  A few error messages were improved.
**Which issue(s) this PR fixes** : 
This fixes CMS-351 https://samsung-cnct.atlassian.net/browse/CMS-351
> delete fix, and moved code to getKubeadmTokenOnMaster

- cloud/ssh/actuators/machine/actuator.go
- cloud/ssh/actuators/machine/actuator_helper.go
- cloud/ssh/sshproviderclient.go
**What this PR does / why we need it**:
This PR creates a kubeconfig secret in the correct namespace for each cluster whose Master has been initialized.  This is needed by the UI (CMA) to return the kubeconfig to the user.
> Create a secret containing the cluster kubeconfig

- README.md
- cloud/ssh/providerconfig/doc.go
- cloud/ssh/providerconfig/v1alpha1/doc.go
There were a couple leftover references to clean up.
> Removes final references to k8s sigs from nonvendor codebase

- clusterctl/examples/ssh/bootstrap_scripts/node_teardown_ubuntu_16.04.template
When you delete the controlplane machine first before deleting the worker node, the worker node was exiting out of it's teardown script because it was trying to run a kubectl command .  This change makes the bash script ignore the command if it errors and continue cleanup.
> allow worker node teardown to complete if master is gone

- cloud/ssh/actuators/machine/actuator_helper.go
- cloud/ssh/actuators/machine/setupconfigs_metadata.go
instead of explicitly getting or setting values via manually entered key names (manually typing these each time), we move the keys to golang constants. Should help avoid typos causing bugs.
> Code clean up, remove manual entries of startup and shutdown script key names.

- cloud/ssh/actuators/machine/actuator.go
- cloud/ssh/actuators/machine/actuator_helper.go
- cloud/ssh/sshproviderclient.go
This allows kubernetes upgrades from versions 1.10.x to 1.11.x.
I did a slight refactor (getMasterSSHClient) to avoid code duplication.
Upgrade version on the controlplane machine first.
Upgrade each worker node machine version individually.
Wait for each machine to be upgraded before upgrading the next one.  You can use kubectl get nodes to see the version of each node. You can also do kubectl describe machine <> --namespace <> to look for a successful Upgrade event: 
Events:
Type    Reason   Age   From                    Message
----    ------   ----  ----                    -------
Normal  Created  30m   ssh-machine-controller  Created Machine ssh-controlplane-mqn7f
Normal  Updated  17m   ssh-machine-controller  Updated Machine ssh-controlplane-mqn7f
> Fixes to update for master and worker nodes

- cloud/ssh/actuators/machine/actuator_helper.go
- clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_ubuntu_16.04.template
- clusterctl/examples/ssh/bootstrap_scripts/node_upgrade_ubuntu_16.04.template
I found a case during update (upgrade) where the kubelet version was installed correctly, but kubelet couldn't start (due to the master being unavailable).  By checking the version from the nodes, we can see what version is truly running.  With this change, update will retry until the version matches what kubectl get nodes tells us is running.  I found that with this change, you can update by not waiting for the master to complete before updating the node versions ...although that would not be best practice.
> check version using kubectl get nodes

- clusterctl/examples/ssh/README.md
- clusterctl/examples/ssh/bootstrap_scripts/master_bootstrap_air_gapped_centos_7.template
- clusterctl/examples/ssh/bootstrap_scripts/master_bootstrap_ubuntu_16.04.template
- clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_air_gapped_centos_7.template
- clusterctl/examples/ssh/bootstrap_scripts/node_bootstrap_ubuntu_16.04.template
- clusterctl/examples/ssh/generate-yaml.sh
Generate requires env vars (e.g. CLUSTER_PRIVATE_KEY) to function. The optional command line option is inconsistent and hidden. This makes all configuration use env vars and stops if unexpected parameters are provided.
Also clarifies why swap should be disabled.
> Make configuration consistent

- clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/common_functions.template
according to the documentation, kubeadm seems to do the cgroupfs driver detection...
since we're upgrading, we're not using kubeadm in the scripts, so the detection fails. This tweak "manually" sets the correct cgroupfs driver to systemd.
> Use sysconfig cgroupfs

- clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/aws/master_teardown.template
- clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/aws/node_teardown.template
- clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/master_teardown.template
- clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/node_teardown.template
- clusterctl/examples/ssh/templates/provider-components.yaml.template
The node needs to be deleted, so it doesn't show up as not ready on the cleanup(delete) of a machine.
> need to delete the node
