.gitignore, clusterctl/examples/ssh/generate-yaml.sh, clusterctl/examples/ssh/machines.yaml.template
updated gitignore file, updated generation code to include machines and cluster (still not correct but we at least have something we can use). We needed at least one validish cluster object and machine object.
=> updated resource generation so that we can advance

cloud/ssh/actuators/machine/actuator.go, cloud/ssh/controllers/machine/controller.go, cloud/ssh/sshproviderclient.go
Here we introduce the important interface and actual struct that implements it. It is our first attempt to getting something that will communicate, natively in go, via ssh and will do so depending on private and public keys given to do so.
=> Added what the SSH client will look like, details are in flux

clusterctl/examples/ssh/provider-components.yaml.template
additional configmap item for machines and their params.
=> added to the provider-components.yaml.template file 

cloud/ssh/actuators/machine/actuator.go, cloud/ssh/actuators/machine/actuator_deployer.go, cloud/ssh/actuators/machine/actuator_helper.go, cloud/ssh/controllers/machine/controller.go
Here we include the pieces that should make the actuator a valid deployer for use with clusterctl.
=> methods making actuator into a deployer

clusterctl/examples/ssh/provider-components.yaml.template
=> Templates should point to quay for now since that is where our

clusterctl/examples/ssh/cluster.yaml.template, clusterctl/examples/ssh/machines.yaml.template, clusterctl/examples/ssh/provider-components.yaml.template
These changes are an attempt to fix subtle and small issues, including things inconsistent with our own types. The source of most of these issues are from the definition changes for the machine type.
=> a few more template changes that conform to current standards.

cloud/ssh/actuators/machine/actuator.go, cloud/ssh/actuators/machine/actuator_helper.go, cloud/ssh/actuators/machine/actuator_status.go, cloud/ssh/controllers/machine/controller.go
This allows us to check if a machine has been created. Blocks implementation of Create.
=> Implement Exists on machine actuator.

clusterctl/examples/ssh/generate-yaml.sh, clusterctl/examples/ssh/provider-components.yaml.template
allows use to create the private key secret for our cluster nodes.
=> updating generation to allow for the cluster private key secret

Makefile, README.md
Just makes the dev_push a little easier
=> Slight Makefile change for dev_push

clusterctl/examples/ssh/bootstrap_scripts/master_ubuntu_16.04.template, clusterctl/examples/ssh/bootstrap_scripts/node_ubuntu_16.04.template, hack/manual-reset-node.sh
fixes a few whitespacing problem, cleans up code, and adds some necessary comments.
=> Small code clean up, additional notes.

README.md, clusterctl/examples/ssh/README.md, clusterctl/examples/ssh/generate-yaml.sh, clusterctl/examples/ssh/machines.yaml.template, clusterctl/examples/ssh/provider-components.yaml.template
=> [CMS-295] Correct documentation to match script. Add TODOs for things we

README.md, clusterctl/examples/ssh/README.md
Added the ssh-agent step, converted ssh key generation to ecdsa instead
of rsa, removed confusing tangental information from instructions.
=> Minor documentation updates

cloud/ssh/actuators/machine/actuator_helper.go, cloud/ssh/actuators/machine/setupconfigs.go, cmd/cluster-controller/main.go, cmd/machine-controller/main.go
Fix or disable various linting issues in preparation for adding linting to the pipeline.
=> Fix linting issues

cloud/ssh/actuators/machine/actuator.go, cloud/ssh/actuators/machine/actuator_helper.go, cloud/ssh/actuators/machine/actuator_status.go, clusterctl/examples/ssh/bootstrap_scripts/master_teardown_ubuntu_16.04.template, clusterctl/examples/ssh/bootstrap_scripts/node_teardown_ubuntu_16.04.template
Changes here are very important in order for delete to occur as it should. Documentation on deletion probably should be created, but that can be for another pr.
=> Changes made to allow delete to complete.

cloud/ssh/actuators/machine/actuator.go, cloud/ssh/actuators/machine/actuator_helper.go, cloud/ssh/actuators/machine/actuator_status.go
Cleaning up logs, fixing small errors in code, moving logic around to be a bit more readable.
=> Refactor updateAnnotations and reformat logs and errors.

cloud/ssh/actuators/machine/configwatch_test.go, cloud/ssh/actuators/machine/setupconfigs.go, cloud/ssh/actuators/machine/setupconfigs_test.go, cloud/ssh/actuators/machine/test_files/fake_machine_setup.yaml
Decided to break up this task into smaller PRs to avoid long delays and unnecessary rebases.
This PR:
- adds tests for configwatch.go
- adds tests for setupcongigs.go
- adds a fake machine config yaml for testing purposes
- documents some of the code in the above files.
=> First unit tests 

cloud/ssh/actuators/machine/actuator.go, cloud/ssh/actuators/machine/actuator_helper.go, cloud/ssh/actuators/machine/setupconfigs_metadata.go
WIP - Please see my TODO comments, it's pretty rough but working.  I'd like to have David's PR 69 merged first as well.
=> create token on master, and check for empty master endpoint

assets/cluster-private-key.yaml, assets/cluster.yaml, assets/machines-formatted.yaml
**What this PR does / why we need it**:
This PR has the correctly formatted manifests needed to create a cluster with kubectl.
Decided to put this in an assets dir, since this is completely separate from clusterctl and it's files.
I would like to point the README to these files.
=> Added sample files to create a cluster with kubectl

clusterctl/examples/ssh/provider-components.yaml.template, cmd/cluster-controller/Dockerfile, cmd/machine-controller/Dockerfile
kubeadm dependency on the host filesystem.
=> Install kubeadm in each container which requires it to remove

clusterctl/examples/ssh/provider-components.yaml.template
set pull policy to be always pull, should help with dev and help update the images.
=> set image pull policy as always full

hack/clean-external-cluster.sh
Removal of secrets as part of clean up script for external cluster.
=> added removal of secrets in clean up script

cloud/ssh/actuators/machine/actuator.go, cloud/ssh/actuators/machine/actuator_deployer.go
PR just cleans up a few typos that I found.
=> fixed a few typos

cloud/ssh/actuators/machine/actuator_helper.go
Update the kubeconfig secret, if it already exists for the cluster.
=> Update secret if it exists

cloud/ssh/actuators/machine/actuator_helper.go
Note: this has not been tested with centos, and ubuntu on MaaS
=> upgrade supports ubuntu and centos

cloud/ssh/actuators/machine/actuator_helper.go, clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_centos_7.template, clusterctl/examples/ssh/bootstrap_scripts/master_upgrade_ubuntu_16.04.template, clusterctl/examples/ssh/bootstrap_scripts/node_upgrade_centos_7.template, clusterctl/examples/ssh/bootstrap_scripts/node_upgrade_ubuntu_16.04.template
I'm testing ubuntu on AWS.  This fixes the grub config change prompt, and versions.
Made sure kubelet upgrade is done last, since dependencies can change the patch version.
Fixed a problem with uncordon in the worker, not using the master ssh client.
=> fixes to upgrade scripts

cloud/ssh/actuators/machine/actuator.go
It needs a unique image tag (not prod) for ssh-machine-controller
=> WIP someone please build locally and push an image to quay.io

clusterctl/examples/ssh/bootstrap_scripts/centos-7.4/sds/common_functions.template
=> Fix kubeadm env
